version: '2'

services:
  mysql:
    image: mysql:5.7
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=pv_erp
      - MYSQL_PASSWORD=pv_erp
      - MYSQL_ROOT_PASSWORD=1234qwer
    ports:
      - 3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=my_user
      - DB_DATABASE=pv_erp
      - DB_PASSWORD=pv_erp
    depends_on: 
      - mysql
    volumes:
      - .:/app
    ports:
      - 8000:8000
